### ISSUE TITLE
The problem about MegaDepth and train

### ISSUE THREAD

**Issue by pfywjk** [Shiaoming/ALIKED#10]
@Shiaoming Hello! Thank you very much for your excellent work. I read your paper the most and want to replicate the code. Here I have two questions：
1.You mentioned that you did not provide a training model, and directly used ALIKE's training model, which will have an impact on the results of later experiments.
2.You use the MegaDepth dataset, I checked that it has about 800G, did you run all this dataset when you ran the experiment? The equipment in our lab cannot support such a large data set, is there any other way?

**Comment by Shiaoming** [comment]
1. The training code of ALIKED is private, but you can refer to ALIKE training code. The main difference is the Sparse NRE loss.
2. I am using the MegaDepth dataset provided by DISK: https://github.com/cvlab-epfl/disk/blob/master/download_dataset
