### ISSUE TITLE
Train Code

### ISSUE THREAD

**Issue by Zhong2017WHU** [Shiaoming/ALIKED#2]
I want to follow your outstanding work, so I wonder if the training code and guideline will be released in the future?

**Comment by zebin-dm** [comment]
ditto

**Comment by Shiaoming** [comment]
I am sorry that I am not allowed to publish the training code of ALIKED, you can refer to the [training code of ALIKE](https://github.com/Shiaoming/ALIKE/raw/main/assets/ALIKE_code.zip).

**Comment by Shiaoming** [comment]
> > I am sorry that I am not allowed to publish the training code of ALIKED, you can refer to the [training code of ALIKE](https://github.com/Shiaoming/ALIKE/raw/main/assets/ALIKE_code.zip).
> 
> This link only contains code and no explanation. I have some questions, can I contact you via email?

sure
