### ISSUE TITLE
Run ALIKED on CPU

### ISSUE THREAD

**Issue by watatata** [Shiaoming/ALIKED#3]
Thank you for releasing ALIKED.

I performed a demo on CPU as follows:

```bash
$ python demo_pair.py assets/st_pauls_cathedral --device cpu
```

Then the following error happened. 

```
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

My PC (MacOS) does not support CUDA.
Is ALIKED not yet CPU-compatible?

**Comment by Shiaoming** [comment]
I have not tested this code on MAC, but CPU mode should be supported on Ubuntu.
