### ISSUE TITLE
Train-code&&Test-code

### ISSUE THREAD

**Issue by Penge666** [Shiaoming/ALIKED#6]
Hello author, reading your article has greatly benefited me. I am also studying feature matching. I have a question to ask you, how should the code for training and testing the ALIKED model be implemented? thanks

**Comment by Shiaoming** [comment]
I am sorry that I am not allowed to publish the training code of ALIKED, you can refer to the [training code of ALIKE](https://github.com/Shiaoming/ALIKE/raw/main/assets/ALIKE_code.zip).
