### ISSUE TITLE
Is it possible to use ALIKED to train matching models (SuperGlue etc)?

### ISSUE THREAD

**Issue by uekoh** [Shiaoming/ALIKED#7]
Hi. 
Thank you for your great job.
The results of your paper have inspired me to change the keypoint detector used to train SuperGlue from SuperPoint to ALIKED.
I believe it will work in principle, what do you think?
I would appreciate your opinion.

https://github.com/magicleap/SuperGluePretrainedNetwork

**Comment by Shiaoming** [comment]
Of course, it's feasible, and can definitely improve the matching accuracy.

**Comment by uekoh** [comment]
Thank you for your response.
Have you tried ALIKED+SuperGlue?

**Comment by Shiaoming** [comment]
Yes

**Comment by uekoh** [comment]
One more question.
Are there any precautions to take when connecting ALIKED and SuperGlue for training? (parameters to be set in ALIKED and SuperGlue, which trained model (ALIKED) to use, etc.).

**Comment by Shiaoming** [comment]
The default conf is a good start.

**Comment by uekoh** [comment]
Thank you! I will try.

**Comment by ducha-aiki** [comment]
https://github.com/cvg/LightGlue has pretrained weights for ALIKED and they are GREAT
https://twitter.com/ducha_aiki/status/1750461472134631829
