### ISSUE TITLE
Regarding processing speed

### ISSUE THREAD

**Issue by uekoh** [Shiaoming/ALIKED#8]
Hi.
I have compared the processing speed between SuperPoint and ALIKED and SuperPoint is faster. 
I have the same input images and number of detection points. 
I used your ALIKED-N(16) model.
What conditions are you measuring in your paper?

![image](https://github.com/Shiaoming/ALIKED/assets/46212278/edf0bbb5-cfa3-44a2-a3db-50cac4096938)

**Comment by Shiaoming** [comment]
NVIDIA RTX 2060. 
I did find that `CUDA_NUM_THREADS` in `get_patches_cuda` on different platforms can lead to differences in runtime. In this paper, this parameter was optimized based on my tests using an RTX 2060.

**Comment by uekoh** [comment]
Thank you for your response.
Do you have any suggestions on how to tune it?
Do I have to raise or lower CUDA_NUM_THREADS and see what the trend is?
In case you are wondering, I am using RTX3060Ti.

**Comment by Shiaoming** [comment]
I don't have any more information for you to refer to regarding this topic.
Mabey you could search for more info about cuda programming~
